//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTrungTamAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuongTrinhKhuyenMai
    {
        public int ID_CTKM { get; set; }
        public string Ten_CTKM { get; set; }
        public int ID_KH { get; set; }
        public System.DateTime ThoiGianBatDau_CTKM { get; set; }
        public System.DateTime ThoiGianKetThuc_CTKM { get; set; }
        public string MoTa_CTKM { get; set; }
    
        public virtual KhoaHoc KhoaHoc { get; set; }
    }
}
