//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTrungTamAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThu
    {
        public int ID_PT { get; set; }
        public string Ma_PT { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public int ID_HV { get; set; }
        public int ID_LH { get; set; }
        public decimal SoTien { get; set; }
        public int ID_NV { get; set; }
    
        public virtual HocVien HocVien { get; set; }
        public virtual LopHoc LopHoc { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
