//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTrungTamAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaikhoanGiaoVien
    {
        public int ID_GV_TK { get; set; }
        public int ID_GV { get; set; }
        public string Username { get; set; }
        public string PassWord { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
