//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTrungTamAnhNgu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiGianLopHoc
    {
        public int ID_LH { get; set; }
        public string Ma_LH { get; set; }
        public string NgayHoc_LH { get; set; }
        public string ThoiGianCuaBuoiHoc { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
    }
}
